### PR TITLE
Delete tutorial/09_qt directory

### PR DESCRIPTION
**Pull request by tkoyama010**
### Overview

Delete tutorial/09_qt directory

 

### Details

- Move the Qt section to trame.

### CODE REVIEW

**Comment by akaszynski** [comment]
I still feel that we need a qt section, at least a brief mention to show how you can use PyVista. MNE, my ``femorph`` library, and several others use ``pyvistaqt`` and QT isn't going away anytime soon. I fully support the usage of Trame, but desktop applications are alive and well for CAE.

**Comment by tkoyama010** [comment]
Copy. I will rewrite it in that policy.

**Comment by akaszynski** [comment]
On second thought, I let's remove this section. I do think it should be mentioned, but we don't need a full section.

**Review by akaszynski — APPROVED** [review]

**Comment by tkoyama010** [comment]
I would integrate the Qt description into the Action section.

**Review by akaszynski — APPROVED** [review]

**Pull request merged**
