### PR TITLE
Update for SciPy23 submission

### PR DESCRIPTION
**Pull request by banesullivan**
@akaszynski, @tkoyama010: please review the latest modifications for a SciPy2023 tutorial.

I've dropped Qt in favor of Jupyter

We need to come up with a cachtier title instead of "PyVista Tutorial" to get folks who may not know what PyVista is. Perhaps:

1. 3D visualization with PyVista
2. From beginner to advanced 3D visualization in Python with PyVista
3. ... suggestions?

### CODE REVIEW

**Comment by banesullivan** [comment]
As we get closer to July, we can update the actual tutorial content.

**Review by tkoyama010 — DISMISSED** [review]
LGTM

**Review by tkoyama010 — DISMISSED** [review]
Thank you for adding trame section.

**Comment by tkoyama010** [comment]
@banesullivan @akaszynski 
Now we have until March 1 to submit your proposal to [#SciPy2023](https://twitter.com/hashtag/SciPy2023?src=hashtag_click)!
https://twitter.com/SciPyConf/status/1626644887419424772
Let's refine our proposals a little more. I am +1 for "3D visualization with PyVista".

**Review by akaszynski — APPROVED** [review]
Fully agree and I see no issues. Agree with dropping qt for trame.

**Comment by banesullivan** [comment]
Submitted!

**Review by tkoyama010 — APPROVED** [review]

**Pull request merged**
